<div class="col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Excluir Ingrediente</h3>
		</div>
		<div class="panel-body">
<form action="<?=SITE?>produto/removerp/" method="POST" id='form' >
	<label for="tamanho">Ingrediente</label>
	<select class="form-control" name="produto" id="produto1">
		<?php foreach($view_dados as $val){ ?>
			<option value="<?=$val->id?>"><?=$val->nome?></option>
		<?php } ?>
	</select>
	<br><button class="btn btn-danger ">
	        <h3>Exluir</h3>
	    </button>
</form>
</div>
</div>
</div>
