<!doctype html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Bruno C. Santos">
	<meta name="generator" content="HXPHP Framework v1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?=$view_title;?></title>
	<link rel="shortcut icon" href="<?=IMG;?>favicon.ico" type="image/x-icon">
	<?=$add_css;?>
	<link rel="stylesheet" href="<?=CSS;?>bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>font-awesome.min.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>style.css" type="text/css">
	<link rel="stylesheet" href="<?=CSS;?>jhlanches.css" type="text/css">
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="<?=JS;?>bootstrap.min.js"></script>
	<link rel="stylesheet" href="<?=SITE?>public/jquery/jquery-ui.min.css">
	<script src="<?=SITE?>public/jquery/external/jquery/jquery.js"></script>
	<script src="<?=SITE?>public/jquery/jquery-ui.min.js"></script>
	<?=$add_js;?>
	<script type="text/javascript" src="<?=JS;?>main.js"></script>
</head>
<body>
		<div class="container-fluid" >
			<a href="<?=SITE?>">
			<img class="logo" src="<?=IMG;?>jheron.jpg" alt=""></a>
		</div>

	<?=$view_message;?>

	<div class="container-fluid">
			<div class="col-md-12">