<script type="text/javascript">
	$(document).ready(function(){
		$("#lanche1").change(function(){
			$.ajax({
				type: "post",
				data: "id="+$("#lanche1").val(),
				dataType: "html",
				url: "<?=SITE?>produto/busca/lanche", 
				success: function(result){
					$("#lanches").hide().html(result).show('slow');
				}});
		});
	})
</script>
<div class="col-md-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Modificar Sanduiche</h3>
		</div>
		<div class="panel-body">
			<form action="<?=SITE?>produto/modificar/lanche" method="POST" id='form'>
				<label for="tamanho">Lanche</label>
				<select class="form-control" name="lanche" id="lanche1">
					<?php foreach($view_dados as $val){ ?>
					<option value="<?=$val->id?>"><?=$val->nome?></option>
					<?php } ?>
				</select>

				<div id="lanches"></div>
			</form>
		</div>
	</div>
</div>
