<script type="text/javascript">
	var GA = function() {};
	GA.prototype.send = function(input) {
        //alert('wohoo, FUNCIONAA!!: ' + input);
	};
	var ga = new GA();
	</script>
	<script type="text/javascript" src="http://rdeveloper.com.br/sharingan/dist/whatsapp-button.js"></script>
<div class="col-md-12">
	<div class="panel panel-default">
	  <div class="panel-body">
	    <h2>Pedido Realizado com sucesso!</h2>
	    <p>Em breve entregeremos em seu endereço</p>
	   	<strong>Gostou do nosso sistema oline?</br>compartilhe com seus amigos!</strong>
		<p>
			<a href="whatsapp://send" onclick="ga.send('btn3');" data-text="Já fiz meu pedido no J.H. Lanches Faça o seu pelo SITE:" data-href="" class="wa_btn wa_btn_l" style="display:none">Compartilhar</a>
		</p>
		<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Compartilhar</a></div>
	
		  </div>
	</div>
</div>